apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-app-clearsessions
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      startingDeadlineSeconds: 15
      ttlSecondsAfterFinished: 100
      template:
        metadata:
          labels:
            app.kubernetes.io/name: django-app
        spec:
          containers:
          - name: django-app-clearsessions-container
            image: django_app
            imagePullPolicy: Never
            command:
              - python
              - manage.py
              - clearsessions
            envFrom:
              - secretRef:
                  name: django-app-configmap
          restartPolicy: Never